


import json
import pandas as pd

# assigns a JSON string to a variable called jess
jess = """
{
    "code": 0,
    "message": "成功",
    "data": {
        "pagination": {
            "page": 0,
            "pageSize": 50,
            "pageCount": 2,
            "total": 85
        },
        "shareHoldingList": [
            {
                "stockId": "78013785970654",
                "symbol": "06110.HK",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "14.49亿",
                "shareHoldingPct": "34.89",
                "lastShareHoldingPct": "34.89",
                "oldShareChange": 0,
                "percentOfPortfolio": "18.72",
                "percentOfShareChange": "0.00",
                "holdingDate": "1677513600",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "06110",
                "stockName": "滔搏",
                "marketLabel": "HK",
                "price": "5.170",
                "priceDirect": "flat",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "76141180439059",
                "symbol": "PDD.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "14.05亿",
                "shareHoldingPct": "0.85",
                "lastShareHoldingPct": "0.89",
                "oldShareChange": 1680600,
                "percentOfPortfolio": "18.15",
                "percentOfShareChange": "+0.12",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+168.06万",
                "sourceGroupName": "13F",
                "stockCode": "PDD",
                "stockName": "拼多多",
                "marketLabel": "US",
                "price": "146.920",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "1680600",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "211644",
                "symbol": "BGNE.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "8.24亿",
                "shareHoldingPct": "4.95",
                "lastShareHoldingPct": "4.96",
                "oldShareChange": -5812573,
                "percentOfPortfolio": "10.65",
                "percentOfShareChange": "-5.56",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-581.26万",
                "sourceGroupName": "多份文件",
                "stockCode": "BGNE",
                "stockName": "百济神州",
                "marketLabel": "US",
                "price": "146.240",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-5812573",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "79310866306388",
                "symbol": "BEKE.US",
                "industryId": "15",
                "industryName": "房地产",
                "shareHoldingValue": "4.08亿",
                "shareHoldingPct": "2.40",
                "lastShareHoldingPct": "2.36",
                "oldShareChange": -42700,
                "percentOfPortfolio": "5.27",
                "percentOfShareChange": "-0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-4.27万",
                "sourceGroupName": "13F",
                "stockCode": "BEKE",
                "stockName": "贝壳",
                "marketLabel": "US",
                "price": "16.970",
                "priceDirect": "flat",
                "shareChangeDirect": "down",
                "shareChangeValue": "-42700",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "79070348137560",
                "symbol": "LEGN.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "3.42亿",
                "shareHoldingPct": "3.28",
                "lastShareHoldingPct": "3.29",
                "oldShareChange": 0,
                "percentOfPortfolio": "4.42",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "LEGN",
                "stockName": "传奇生物",
                "marketLabel": "US",
                "price": "40.030",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "201345",
                "symbol": "MSFT.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "2.93亿",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": -37300,
                "percentOfPortfolio": "3.79",
                "percentOfShareChange": "-0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-3.73万",
                "sourceGroupName": "13F",
                "stockCode": "MSFT",
                "stockName": "微软",
                "marketLabel": "US",
                "price": "413.520",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-37300",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "53291954211667",
                "symbol": "02899.HK",
                "industryId": "5",
                "industryName": "有色金属",
                "shareHoldingValue": "2.81亿",
                "shareHoldingPct": "0.54",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 0,
                "percentOfPortfolio": "3.63",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "02899",
                "stockName": "紫金矿业",
                "marketLabel": "HK",
                "price": "16.700",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "69831873267850",
                "symbol": "02186.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1.93亿",
                "shareHoldingPct": "14.68",
                "lastShareHoldingPct": "14.68",
                "oldShareChange": 0,
                "percentOfPortfolio": "2.49",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "02186",
                "stockName": "绿叶制药",
                "marketLabel": "HK",
                "price": "2.840",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "205816",
                "symbol": "AMD.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "1.67亿",
                "shareHoldingPct": "0.06",
                "lastShareHoldingPct": "0.06",
                "oldShareChange": 912400,
                "percentOfPortfolio": "2.16",
                "percentOfShareChange": "+0.06",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+91.24万",
                "sourceGroupName": "13F",
                "stockCode": "AMD",
                "stockName": "美国超微公司",
                "marketLabel": "US",
                "price": "163.550",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "912400",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "205111",
                "symbol": "AMZN.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "1.49亿",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": 11000,
                "percentOfPortfolio": "1.92",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+1.10万",
                "sourceGroupName": "13F",
                "stockCode": "AMZN",
                "stockName": "亚马逊",
                "marketLabel": "US",
                "price": "178.340",
                "priceDirect": "up",
                "shareChangeDirect": "up",
                "shareChangeValue": "11000",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "75874892466505",
                "symbol": "KNSA.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1.46亿",
                "shareHoldingPct": "10.47",
                "lastShareHoldingPct": "10.52",
                "oldShareChange": 3550213,
                "percentOfPortfolio": "1.89",
                "percentOfShareChange": "+5.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+355.02万",
                "sourceGroupName": "多份文件",
                "stockCode": "KNSA",
                "stockName": "Kiniksa Pharmaceuticals",
                "marketLabel": "US",
                "price": "19.710",
                "priceDirect": "up",
                "shareChangeDirect": "up",
                "shareChangeValue": "3550213",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "205513",
                "symbol": "CRM.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "1.40亿",
                "shareHoldingPct": "0.05",
                "lastShareHoldingPct": "0.05",
                "oldShareChange": -285400,
                "percentOfPortfolio": "1.80",
                "percentOfShareChange": "-0.03",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-28.54万",
                "sourceGroupName": "13F",
                "stockCode": "CRM",
                "stockName": "赛富时",
                "marketLabel": "US",
                "price": "236.620",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-285400",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "79882096745297",
                "symbol": "06993.HK",
                "industryId": "11",
                "industryName": "轻工制造",
                "shareHoldingValue": "1.28亿",
                "shareHoldingPct": "8.56",
                "lastShareHoldingPct": "8.56",
                "oldShareChange": -26542800,
                "percentOfPortfolio": "1.66",
                "percentOfShareChange": "-0.45",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-2654.28万",
                "sourceGroupName": "年报",
                "stockCode": "06993",
                "stockName": "蓝月亮集团",
                "marketLabel": "HK",
                "price": "2.020",
                "priceDirect": "flat",
                "shareChangeDirect": "down",
                "shareChangeValue": "-26542800",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "78731045512945",
                "symbol": "09969.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1.24亿",
                "shareHoldingPct": "11.85",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 0,
                "percentOfPortfolio": "1.60",
                "percentOfShareChange": "0.00",
                "holdingDate": "1672416000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "09969",
                "stockName": "诺诚健华",
                "marketLabel": "HK",
                "price": "4.550",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "63887638528853",
                "symbol": "00853.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1.23亿",
                "shareHoldingPct": "8.02",
                "lastShareHoldingPct": "8.03",
                "oldShareChange": -153694000,
                "percentOfPortfolio": "1.59",
                "percentOfShareChange": "-8.39",
                "holdingDate": "1672416000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-1.54亿",
                "sourceGroupName": "年报",
                "stockCode": "00853",
                "stockName": "微创医疗",
                "marketLabel": "HK",
                "price": "6.280",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-153694000",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "201378",
                "symbol": "TTWO.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "1.17亿",
                "shareHoldingPct": "0.46",
                "lastShareHoldingPct": "0.46",
                "oldShareChange": 0,
                "percentOfPortfolio": "1.52",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "TTWO",
                "stockName": "Take-Two互动软件",
                "marketLabel": "US",
                "price": "163.640",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "202639",
                "symbol": "DHR.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1.17亿",
                "shareHoldingPct": "0.06",
                "lastShareHoldingPct": "0.06",
                "oldShareChange": 0,
                "percentOfPortfolio": "1.51",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "DHR",
                "stockName": "丹纳赫",
                "marketLabel": "US",
                "price": "261.380",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "65657165055254",
                "symbol": "01302.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "9313.81万",
                "shareHoldingPct": "8.94",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 0,
                "percentOfPortfolio": "1.20",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "01302",
                "stockName": "先健科技",
                "marketLabel": "HK",
                "price": "1.670",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "83266531196149",
                "symbol": "GPCR.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "8520.90万",
                "shareHoldingPct": "4.47",
                "lastShareHoldingPct": "4.47",
                "oldShareChange": 0,
                "percentOfPortfolio": "1.10",
                "percentOfShareChange": "0.00",
                "holdingDate": "1678809600",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "GPCR",
                "stockName": "硕迪生物",
                "marketLabel": "US",
                "price": "52.740",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "79813377480734",
                "symbol": "DASH.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "8066.38万",
                "shareHoldingPct": "0.14",
                "lastShareHoldingPct": "0.14",
                "oldShareChange": -449300,
                "percentOfPortfolio": "1.04",
                "percentOfShareChange": "-0.11",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-44.93万",
                "sourceGroupName": "13F",
                "stockCode": "DASH",
                "stockName": "DoorDash",
                "marketLabel": "US",
                "price": "110.820",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-449300",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "84799834526330",
                "symbol": "AVBP.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "7194.21万",
                "shareHoldingPct": "11.73",
                "lastShareHoldingPct": "11.73",
                "oldShareChange": 3929117,
                "percentOfPortfolio": "0.93",
                "percentOfShareChange": "+11.73",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+392.91万",
                "sourceGroupName": "13F",
                "stockCode": "AVBP",
                "stockName": "ArriVent BioPharma",
                "marketLabel": "US",
                "price": "19.190",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "3929117",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "76772540417877",
                "symbol": "01877.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "7131.54万",
                "shareHoldingPct": "5.74",
                "lastShareHoldingPct": "5.74",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.92",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "01877",
                "stockName": "君实生物",
                "marketLabel": "HK",
                "price": "12.140",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "83099027245477",
                "symbol": "02469.HK",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "6239.97万",
                "shareHoldingPct": "5.01",
                "lastShareHoldingPct": "5.01",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.81",
                "percentOfShareChange": "0.00",
                "holdingDate": "1687708800",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "交易所公告",
                "stockCode": "02469",
                "stockName": "粉笔",
                "marketLabel": "HK",
                "price": "4.250",
                "priceDirect": "flat",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "205368",
                "symbol": "MCO.US",
                "industryId": "19",
                "industryName": "非银金融",
                "shareHoldingValue": "6125.85万",
                "shareHoldingPct": "0.09",
                "lastShareHoldingPct": "0.09",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.79",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "MCO",
                "stockName": "穆迪",
                "marketLabel": "US",
                "price": "401.650",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "43611097924498",
                "symbol": "00914.HK",
                "industryId": "21",
                "industryName": "建筑材料",
                "shareHoldingValue": "6061.51万",
                "shareHoldingPct": "0.59",
                "lastShareHoldingPct": "0.59",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.78",
                "percentOfShareChange": "0.00",
                "holdingDate": "1680192000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "巨潮定期披露",
                "stockCode": "00914",
                "stockName": "海螺水泥",
                "marketLabel": "HK",
                "price": "18.480",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80753975101554",
                "symbol": "02162.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "5940.94万",
                "shareHoldingPct": "4.96",
                "lastShareHoldingPct": "4.96",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.77",
                "percentOfShareChange": "0.00",
                "holdingDate": "1679587200",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "交易所公告",
                "stockCode": "02162",
                "stockName": "康诺亚-B",
                "marketLabel": "HK",
                "price": "33.900",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "79766132840407",
                "symbol": "YSG.US",
                "industryId": "11",
                "industryName": "轻工制造",
                "shareHoldingValue": "5030.15万",
                "shareHoldingPct": "20.85",
                "lastShareHoldingPct": "20.39",
                "oldShareChange": -1,
                "percentOfPortfolio": "0.65",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-1.00",
                "sourceGroupName": "多份文件",
                "stockCode": "YSG",
                "stockName": "逸仙电商",
                "marketLabel": "US",
                "price": "3.1700",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-1",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "75187697485565",
                "symbol": "01789.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "4761.48万",
                "shareHoldingPct": "6.75",
                "lastShareHoldingPct": "6.75",
                "oldShareChange": -2664400,
                "percentOfPortfolio": "0.62",
                "percentOfShareChange": "-0.24",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-266.44万",
                "sourceGroupName": "年报",
                "stockCode": "01789",
                "stockName": "爱康医疗",
                "marketLabel": "HK",
                "price": "5.220",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-2664400",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "81226421726841",
                "symbol": "ENFN.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "4597.07万",
                "shareHoldingPct": "5.41",
                "lastShareHoldingPct": "5.54",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.59",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "ENFN",
                "stockName": "Enfusion",
                "marketLabel": "US",
                "price": "9.160",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "80861349505874",
                "symbol": "CTKB.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "4460.21万",
                "shareHoldingPct": "5.07",
                "lastShareHoldingPct": "5.09",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.58",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "CTKB",
                "stockName": "Cytek Biosciences",
                "marketLabel": "US",
                "price": "5.530",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "77584289451605",
                "symbol": "BBIO.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "4099.73万",
                "shareHoldingPct": "0.73",
                "lastShareHoldingPct": "0.74",
                "oldShareChange": -23751,
                "percentOfPortfolio": "0.53",
                "percentOfShareChange": "-0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-2.38万",
                "sourceGroupName": "13F",
                "stockCode": "BBIO",
                "stockName": "BridgeBio Pharma",
                "marketLabel": "US",
                "price": "28.980",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-23751",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "201799",
                "symbol": "HTHT.US",
                "industryId": "17",
                "industryName": "休闲服务",
                "shareHoldingValue": "3659.45万",
                "shareHoldingPct": "0.30",
                "lastShareHoldingPct": "0.29",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.47",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "HTHT",
                "stockName": "华住",
                "marketLabel": "US",
                "price": "36.640",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "48361331754626",
                "symbol": "01666.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "2966.01万",
                "shareHoldingPct": "3.72",
                "lastShareHoldingPct": "3.72",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.38",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "01666",
                "stockName": "同仁堂科技",
                "marketLabel": "HK",
                "price": "5.370",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "78331613550497",
                "symbol": "06049.HK",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "2540.34万",
                "shareHoldingPct": "1.42",
                "lastShareHoldingPct": "1.42",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.33",
                "percentOfShareChange": "0.00",
                "holdingDate": "1672416000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "06049",
                "stockName": "保利物业",
                "marketLabel": "HK",
                "price": "33.250",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "83288006032668",
                "symbol": "HSAI.US",
                "industryId": "7",
                "industryName": "汽车",
                "shareHoldingValue": "2478.78万",
                "shareHoldingPct": "3.72",
                "lastShareHoldingPct": "3.78",
                "oldShareChange": -715000,
                "percentOfPortfolio": "0.32",
                "percentOfShareChange": "-0.56",
                "holdingDate": "1709568000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-71.50万",
                "sourceGroupName": "13G",
                "stockCode": "HSAI",
                "stockName": "Hesai",
                "marketLabel": "US",
                "price": "4.840",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-715000",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "79572859099990",
                "symbol": "06998.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "2000.22万",
                "shareHoldingPct": "24.74",
                "lastShareHoldingPct": "25.04",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.26",
                "percentOfShareChange": "0.00",
                "holdingDate": "1712678400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "交易所公告",
                "stockCode": "06998",
                "stockName": "嘉和生物-B",
                "marketLabel": "HK",
                "price": "1.270",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "80187039636248",
                "symbol": "CPNG.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "1950.13万",
                "shareHoldingPct": "0.06",
                "lastShareHoldingPct": "0.06",
                "oldShareChange": -1146300,
                "percentOfPortfolio": "0.25",
                "percentOfShareChange": "-0.06",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-114.63万",
                "sourceGroupName": "13F",
                "stockCode": "CPNG",
                "stockName": "Coupang",
                "marketLabel": "US",
                "price": "22.530",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-1146300",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "80307298704613",
                "symbol": "EM.US",
                "industryId": "29",
                "industryName": "其他",
                "shareHoldingValue": "1908.67万",
                "shareHoldingPct": "12.08",
                "lastShareHoldingPct": "1.52",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.25",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "EM",
                "stockName": "怪兽充电",
                "marketLabel": "US",
                "price": "0.9750",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "78967268714252",
                "symbol": "09996.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1905.26万",
                "shareHoldingPct": "6.03",
                "lastShareHoldingPct": "6.03",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.25",
                "percentOfShareChange": "0.00",
                "holdingDate": "1701792000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "交易所公告",
                "stockCode": "09996",
                "stockName": "沛嘉医疗-B",
                "marketLabel": "HK",
                "price": "3.660",
                "priceDirect": "flat",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "205354",
                "symbol": "BIDU.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "1633.11万",
                "shareHoldingPct": "0.04",
                "lastShareHoldingPct": "0.04",
                "oldShareChange": -384800,
                "percentOfPortfolio": "0.21",
                "percentOfShareChange": "-0.11",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-38.48万",
                "sourceGroupName": "13F",
                "stockCode": "BIDU",
                "stockName": "百度",
                "marketLabel": "US",
                "price": "95.670",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-384800",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "201088",
                "symbol": "NTES.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "1477.69万",
                "shareHoldingPct": "0.02",
                "lastShareHoldingPct": "0.02",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.19",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "NTES",
                "stockName": "网易",
                "marketLabel": "US",
                "price": "88.310",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "81071802903796",
                "symbol": "ONON.US",
                "industryId": "10",
                "industryName": "纺织服装",
                "shareHoldingValue": "1448.95万",
                "shareHoldingPct": "0.13",
                "lastShareHoldingPct": "0.13",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.19",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "ONON",
                "stockName": "昂跑",
                "marketLabel": "US",
                "price": "41.240",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "202687",
                "symbol": "MDLZ.US",
                "industryId": "9",
                "industryName": "食品饮料",
                "shareHoldingValue": "1369.31万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": -173900,
                "percentOfPortfolio": "0.18",
                "percentOfShareChange": "-0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-17.39万",
                "sourceGroupName": "13F",
                "stockCode": "MDLZ",
                "stockName": "亿滋",
                "marketLabel": "US",
                "price": "67.350",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-173900",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "212271",
                "symbol": "ZTO.US",
                "industryId": "14",
                "industryName": "交通运输",
                "shareHoldingValue": "1361.98万",
                "shareHoldingPct": "0.08",
                "lastShareHoldingPct": "0.08",
                "oldShareChange": -160000,
                "percentOfPortfolio": "0.18",
                "percentOfShareChange": "-0.02",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-16.00万",
                "sourceGroupName": "13F",
                "stockCode": "ZTO",
                "stockName": "中通快递",
                "marketLabel": "US",
                "price": "23.140",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-160000",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "78275779187254",
                "symbol": "IMAB.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1250.57万",
                "shareHoldingPct": "8.56",
                "lastShareHoldingPct": "8.56",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.16",
                "percentOfShareChange": "0.00",
                "holdingDate": "1713110400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "IMAB",
                "stockName": "I-Mab",
                "marketLabel": "US",
                "price": "1.580",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "79164837409186",
                "symbol": "API.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "1229.57万",
                "shareHoldingPct": "5.28",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": -178175,
                "percentOfPortfolio": "0.16",
                "percentOfShareChange": "-0.20",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-17.82万",
                "sourceGroupName": "13G",
                "stockCode": "API",
                "stockName": "声网",
                "marketLabel": "US",
                "price": "2.390",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-178175",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "202597",
                "symbol": "NVDA.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "1228.94万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 13600,
                "percentOfPortfolio": "0.16",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+1.36万",
                "sourceGroupName": "13F",
                "stockCode": "NVDA",
                "stockName": "英伟达",
                "marketLabel": "US",
                "price": "1150.000",
                "priceDirect": "up",
                "shareChangeDirect": "up",
                "shareChangeValue": "13600",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "79903571575951",
                "symbol": "01167.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "1177.05万",
                "shareHoldingPct": "7.18",
                "lastShareHoldingPct": "7.18",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.15",
                "percentOfShareChange": "0.00",
                "holdingDate": "1672416000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "01167",
                "stockName": "加科思-B",
                "marketLabel": "HK",
                "price": "1.770",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "210182",
                "symbol": "BABA.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "1055.79万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": -1076718,
                "percentOfPortfolio": "0.14",
                "percentOfShareChange": "-0.04",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-107.67万",
                "sourceGroupName": "13F",
                "stockCode": "BABA",
                "stockName": "阿里巴巴",
                "marketLabel": "US",
                "price": "77.900",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-1076718",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "78967268714239",
                "symbol": "09983.HK",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "997.56万",
                "shareHoldingPct": "6.64",
                "lastShareHoldingPct": "6.64",
                "oldShareChange": -10000,
                "percentOfPortfolio": "0.13",
                "percentOfShareChange": "-0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-1.00万",
                "sourceGroupName": "年报",
                "stockCode": "09983",
                "stockName": "建业新生活",
                "marketLabel": "HK",
                "price": "1.360",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-10000",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "74968654356875",
                "symbol": "SE.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "926.79万",
                "shareHoldingPct": "0.03",
                "lastShareHoldingPct": "0.03",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.12",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "SE",
                "stockName": "Sea",
                "marketLabel": "US",
                "price": "69.080",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "206647",
                "symbol": "GOOGL.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "915.84万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 58900,
                "percentOfPortfolio": "0.12",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+5.89万",
                "sourceGroupName": "13F",
                "stockCode": "GOOGL",
                "stockName": "谷歌-A",
                "marketLabel": "US",
                "price": "172.380",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "58900",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80414672891322",
                "symbol": "APP.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "904.35万",
                "shareHoldingPct": "0.04",
                "lastShareHoldingPct": "0.04",
                "oldShareChange": 130800,
                "percentOfPortfolio": "0.12",
                "percentOfShareChange": "+0.04",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+13.08万",
                "sourceGroupName": "13F",
                "stockCode": "APP",
                "stockName": "Applovin",
                "marketLabel": "US",
                "price": "82.260",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "130800",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "206117",
                "symbol": "MU.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "896.20万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": 72100,
                "percentOfPortfolio": "0.12",
                "percentOfShareChange": "+0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+7.21万",
                "sourceGroupName": "13F",
                "stockCode": "MU",
                "stockName": "美光科技",
                "marketLabel": "US",
                "price": "126.595",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "72100",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "81277961111701",
                "symbol": "02197.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "862.30万",
                "shareHoldingPct": "12.69",
                "lastShareHoldingPct": "12.69",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.11",
                "percentOfShareChange": "0.00",
                "holdingDate": "1672416000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "02197",
                "stockName": "三叶草生物-B",
                "marketLabel": "HK",
                "price": "0.405",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "84855669101290",
                "symbol": "MGX.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "841.54万",
                "shareHoldingPct": "2.08",
                "lastShareHoldingPct": "2.08",
                "oldShareChange": 777768,
                "percentOfPortfolio": "0.11",
                "percentOfShareChange": "+2.08",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+77.78万",
                "sourceGroupName": "13F",
                "stockCode": "MGX",
                "stockName": "Metagenomi Technologies, LLC",
                "marketLabel": "US",
                "price": "6.690",
                "priceDirect": "flat",
                "shareChangeDirect": "up",
                "shareChangeValue": "777768",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "201532",
                "symbol": "SOHU.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "766.91万",
                "shareHoldingPct": "2.21",
                "lastShareHoldingPct": "2.21",
                "oldShareChange": -18400,
                "percentOfPortfolio": "0.10",
                "percentOfShareChange": "-0.06",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-1.84万",
                "sourceGroupName": "13F",
                "stockCode": "SOHU",
                "stockName": "搜狐",
                "marketLabel": "US",
                "price": "12.465",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-18400",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "76965814160543",
                "symbol": "GOSS.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "631.70万",
                "shareHoldingPct": "2.20",
                "lastShareHoldingPct": "2.20",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.08",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "GOSS",
                "stockName": "Gossamer Bio",
                "marketLabel": "US",
                "price": "0.591",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "80453327395294",
                "symbol": "06622.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "618.34万",
                "shareHoldingPct": "5.61",
                "lastShareHoldingPct": "5.61",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.08",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "06622",
                "stockName": "兆科眼科-B",
                "marketLabel": "HK",
                "price": "1.470",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "202382",
                "symbol": "MRVL.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "435.17万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": 59500,
                "percentOfPortfolio": "0.06",
                "percentOfShareChange": "+0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+5.95万",
                "sourceGroupName": "13F",
                "stockCode": "MRVL",
                "stockName": "迈威尔科技",
                "marketLabel": "US",
                "price": "66.770",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "59500",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "83953725966425",
                "symbol": "SGMT.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "379.07万",
                "shareHoldingPct": "2.27",
                "lastShareHoldingPct": "2.27",
                "oldShareChange": -724743,
                "percentOfPortfolio": "0.05",
                "percentOfShareChange": "-2.27",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-72.47万",
                "sourceGroupName": "13F",
                "stockCode": "SGMT",
                "stockName": "Sagimet Biosciences",
                "marketLabel": "US",
                "price": "5.175",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-724743",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "201274",
                "symbol": "VIPS.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "347.15万",
                "shareHoldingPct": "0.04",
                "lastShareHoldingPct": "0.04",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "VIPS",
                "stockName": "唯品会",
                "marketLabel": "US",
                "price": "16.400",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "207740",
                "symbol": "PACB.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "335.40万",
                "shareHoldingPct": "0.34",
                "lastShareHoldingPct": "0.34",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "PACB",
                "stockName": "Pacific Biosciences of California",
                "marketLabel": "US",
                "price": "1.805",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "78602196701985",
                "symbol": "VRT.US",
                "industryId": "24",
                "industryName": "机械设备",
                "shareHoldingValue": "307.13万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": 38200,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "+0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+3.82万",
                "sourceGroupName": "13F",
                "stockCode": "VRT",
                "stockName": "Vertiv Holdings",
                "marketLabel": "US",
                "price": "92.060",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "38200",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "82252918909550",
                "symbol": "META.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "294.81万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 6000,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+6000.00",
                "sourceGroupName": "13F",
                "stockCode": "META",
                "stockName": "Meta Platforms",
                "marketLabel": "US",
                "price": "475.400",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "6000",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80307298720856",
                "symbol": "TUYA.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "289.41万",
                "shareHoldingPct": "0.28",
                "lastShareHoldingPct": "0.28",
                "oldShareChange": -35300,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "-0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-3.53万",
                "sourceGroupName": "13F",
                "stockCode": "TUYA",
                "stockName": "涂鸦智能",
                "marketLabel": "US",
                "price": "1.895",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-35300",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "201429",
                "symbol": "AVGO.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "283.55万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 2100,
                "percentOfPortfolio": "0.04",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+2100.00",
                "sourceGroupName": "13F",
                "stockCode": "AVGO",
                "stockName": "博通",
                "marketLabel": "US",
                "price": "1313.635",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "2100",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "203173",
                "symbol": "GE.US",
                "industryId": "25",
                "industryName": "国防军工",
                "shareHoldingValue": "262.46万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 18800,
                "percentOfPortfolio": "0.03",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+1.88万",
                "sourceGroupName": "13F",
                "stockCode": "GE",
                "stockName": "GE航天航空",
                "marketLabel": "US",
                "price": "160.990",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "18800",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "205189",
                "symbol": "AAPL.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "198.66万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 11700,
                "percentOfPortfolio": "0.03",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+1.17万",
                "sourceGroupName": "13F",
                "stockCode": "AAPL",
                "stockName": "苹果",
                "marketLabel": "US",
                "price": "193.410",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "11700",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "74277164630235",
                "symbol": "BEDU.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "189.72万",
                "shareHoldingPct": "3.32",
                "lastShareHoldingPct": "3.32",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "BEDU",
                "stockName": "博实乐教育",
                "marketLabel": "US",
                "price": "2.2900",
                "priceDirect": "flat",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "81196356955719",
                "symbol": "PYXS.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "183.27万",
                "shareHoldingPct": "0.65",
                "lastShareHoldingPct": "0.66",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "PYXS",
                "stockName": "Pyxis Oncology",
                "marketLabel": "US",
                "price": "3.650",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "79658758657832",
                "symbol": "ALGS.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "181.36万",
                "shareHoldingPct": "2.44",
                "lastShareHoldingPct": "2.52",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "ALGS",
                "stockName": "Aligos Therapeutics",
                "marketLabel": "US",
                "price": "0.605",
                "priceDirect": "down",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "210029",
                "symbol": "JD.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "165.29万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": -1389900,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "-0.09",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-138.99万",
                "sourceGroupName": "13F",
                "stockCode": "JD",
                "stockName": "京东",
                "marketLabel": "US",
                "price": "30.025",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-1389900",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "80607946415597",
                "symbol": "BZ.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "164.12万",
                "shareHoldingPct": "0.02",
                "lastShareHoldingPct": "0.02",
                "oldShareChange": -34600,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "-0.01",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-3.46万",
                "sourceGroupName": "13F",
                "stockCode": "BZ",
                "stockName": "BOSS直聘",
                "marketLabel": "US",
                "price": "21.505",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-34600",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "76660871482369",
                "symbol": "MOGU.US",
                "industryId": "16",
                "industryName": "商业贸易",
                "shareHoldingValue": "161.03万",
                "shareHoldingPct": "10.32",
                "lastShareHoldingPct": "10.32",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "MOGU",
                "stockName": "蘑菇街",
                "marketLabel": "US",
                "price": "2.393",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80114024974458",
                "symbol": "02170.HK",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "154.26万",
                "shareHoldingPct": "2.20",
                "lastShareHoldingPct": "2.20",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.02",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "年报",
                "stockCode": "02170",
                "stockName": "贝康医疗-B",
                "marketLabel": "HK",
                "price": "2.050",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "210098",
                "symbol": "ANET.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "107.91万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 3600,
                "percentOfPortfolio": "0.01",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+3600.00",
                "sourceGroupName": "13F",
                "stockCode": "ANET",
                "stockName": "Arista Networks",
                "marketLabel": "US",
                "price": "295.120",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "3600",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80680960879011",
                "symbol": "ATAT.US",
                "industryId": "17",
                "industryName": "休闲服务",
                "shareHoldingValue": "92.85万",
                "shareHoldingPct": "0.04",
                "lastShareHoldingPct": "0.04",
                "oldShareChange": -150000,
                "percentOfPortfolio": "0.01",
                "percentOfShareChange": "-0.11",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-15.00万",
                "sourceGroupName": "13F",
                "stockCode": "ATAT",
                "stockName": "亚朵",
                "marketLabel": "US",
                "price": "17.880",
                "priceDirect": "down",
                "shareChangeDirect": "down",
                "shareChangeValue": "-150000",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "75625784363178",
                "symbol": "IQ.US",
                "industryId": "27",
                "industryName": "互联网与传媒",
                "shareHoldingValue": "61.13万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.01",
                "percentOfShareChange": "0.00",
                "holdingDate": "1703952000",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "IQ",
                "stockName": "爱奇艺",
                "marketLabel": "US",
                "price": "4.545",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "up"
            },
            {
                "stockId": "85341000415044",
                "symbol": "LSB.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "54.50万",
                "shareHoldingPct": "0.40",
                "lastShareHoldingPct": "0.40",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.01",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "LSB",
                "stockName": "LakeShore Biopharma",
                "marketLabel": "US",
                "price": "0.935",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "203134",
                "symbol": "QCOM.US",
                "industryId": "6",
                "industryName": "电子",
                "shareHoldingValue": "51.31万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 3000,
                "percentOfPortfolio": "0.01",
                "percentOfShareChange": "+0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+3000.00",
                "sourceGroupName": "13F",
                "stockCode": "QCOM",
                "stockName": "高通",
                "marketLabel": "US",
                "price": "204.200",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "3000",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "80633716238696",
                "symbol": "YMM.US",
                "industryId": "26",
                "industryName": "计算机",
                "shareHoldingValue": "9.93万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": -2239023,
                "percentOfPortfolio": "0.00",
                "percentOfShareChange": "-0.21",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "-223.90万",
                "sourceGroupName": "13F",
                "stockCode": "YMM",
                "stockName": "满帮",
                "marketLabel": "US",
                "price": "8.880",
                "priceDirect": "up",
                "shareChangeDirect": "down",
                "shareChangeValue": "-2239023",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "201340",
                "symbol": "CJJD.US",
                "industryId": "12",
                "industryName": "医药生物",
                "shareHoldingValue": "6.53万",
                "shareHoldingPct": "0.66",
                "lastShareHoldingPct": "1.20",
                "oldShareChange": 1,
                "percentOfPortfolio": "0.00",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+1.00",
                "sourceGroupName": "13F",
                "stockCode": "CJJD",
                "stockName": "九洲大药房",
                "marketLabel": "US",
                "price": "2.6201",
                "priceDirect": "flat",
                "shareChangeDirect": "up",
                "shareChangeValue": "1",
                "shareHoldingPctDirect": "down"
            },
            {
                "stockId": "81707458042746",
                "symbol": "CEG.US",
                "industryId": "13",
                "industryName": "公用事业",
                "shareHoldingValue": "5.57万",
                "shareHoldingPct": "0.00",
                "lastShareHoldingPct": "0.00",
                "oldShareChange": 300,
                "percentOfPortfolio": "0.00",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "+300.00",
                "sourceGroupName": "13F",
                "stockCode": "CEG",
                "stockName": "Constellation Energy",
                "marketLabel": "US",
                "price": "207.925",
                "priceDirect": "down",
                "shareChangeDirect": "up",
                "shareChangeValue": "300",
                "shareHoldingPctDirect": "flat"
            },
            {
                "stockId": "76003741485499",
                "symbol": "UXIN.US",
                "industryId": "7",
                "industryName": "汽车",
                "shareHoldingValue": "4.00万",
                "shareHoldingPct": "0.01",
                "lastShareHoldingPct": "0.01",
                "oldShareChange": 0,
                "percentOfPortfolio": "0.00",
                "percentOfShareChange": "0.00",
                "holdingDate": "1711814400",
                "ownerObjectId": 39335212,
                "ownerObjectName": "高瓴资本",
                "shareChange": "0.00",
                "sourceGroupName": "13F",
                "stockCode": "UXIN",
                "stockName": "优信",
                "marketLabel": "US",
                "price": "2.3000",
                "priceDirect": "up",
                "shareChangeDirect": "flat",
                "shareChangeValue": "0",
                "shareHoldingPctDirect": "flat"
            }
        ]
    }
}
"""



# parses the data and assigns it to a variable called jess_dict
jess_dict = json.loads(jess)

# Printed output: {"name": "Jessica Wilkins", "hobbies": ["music", "watching TV", "hanging out with friends"]}
# print(jess_dict["data"]["shareHoldingList"])

stock_list = jess_dict["data"]["shareHoldingList"]
stock_a_pool = []
stock_us_pool = []
stock_hk_pool = []
for stock in stock_list:
    # print(stock['ownerObjectName'])
    # print(stock['symbol'])
    if stock['marketLabel'] == 'US':
        symbol = 'us'+stock['symbol'][:-3]
        stock_us_pool.append({"name":stock['stockName'], "symbol":symbol})
    elif stock['marketLabel'] == 'HK':
        symbol = 'hk' + stock['symbol'][:-3]
        stock_hk_pool.append({"name":stock['stockName'], "symbol":symbol})
    else:
        stock_a_pool.append({"name":stock['stockName'], "symbol":symbol})

stock_a_pd = pd.DataFrame(stock_a_pool)
stock_us_pd = pd.DataFrame(stock_us_pool)
stock_hk_pd = pd.DataFrame(stock_hk_pool)
stock_a_pd.to_csv("stock_a_pool.csv")
stock_us_pd.to_csv("stock_us_pool.csv")
stock_hk_pd.to_csv("stock_hk_pool.csv")

# ss = "MCO.US"
# print(ss[:-3])